### ISSUE TITLE
Conjur SecretUsernameCredential is using method password as default

### ISSUE THREAD

**Issue by guygiat** [cyberark/conjur-credentials-plugin#10]
When using Conjur SecretUsenameCredential with Jenkins master and slave and fetching the ssh key from Conjur, the Jenkins master refers the ssh key as a password object instead of a ssh key.

# Way to reproduce
1. Configure a linux machine to support both password and ssh authentication and try to use Conjur SecretUsenameCredential to fetch a ssh key and use it for master/slave connection.
1. The process will fail saying that the password is incorrect with the syntax "method:password"
1. Disable password authentication on the slave linux machine and try again and the handshake will now work.

# Proposed solution
Create a dedicated ssh key Conjur credential object that can be used as Jenkins credential.

**Comment by AndrewCopeland** [comment]
This has been resolved in: https://github.com/cyberark/conjur-credentials-plugin/pull/13

The username and ssh key credentials have been decoupled. This now means the conjur credential plugin has 3 credential types:
- Conjur Secret
- Conjur Username Secret
- Conjur Username SSH Key Secret
