### ISSUE TITLE
Git Plugin doesn't show up the conjur secret type credentials in dropdown

### ISSUE THREAD

**Issue by dhruvservana** [cyberark/conjur-credentials-plugin#7]
Git under Source code management not allowing to choose conjur secret type credentails

**Comment by AndrewCopeland** [comment]
When using the GIT you must provider a Conjur Username Credential or Conjur Username SSH Key Credential. However remember that it is not possible to use this credential type within a folder when the credentials are also stored in the folder level. This is a jenkins limitations in which the git plugin cannot retrieve the context (Where it is being run).
